web:
  build: .
  command: "runserver 0.0.0.0:8010"
  environment:
      PYTHONUNBUFFERED: 0
      DJANGO_SETTINGS_MODULE: banking.settings.base
  entrypoint:
   - './manage.py'
  links:
   - db
  volumes:
   - .:/opt/code
  ports:
   - "8010:8010"
data:
  image: aexea/aexea-base
  volumes:
    - /home/uid1000
db:
  image: postgres:9.4
